[package]
name = "async_ex2"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.0.0-beta.21", features = ["openssl"] }
env_logger = "0.9"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.39"
