[package]
name = "nested-routing"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
env_logger = "0.10"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.39"
