[package]
name = "tls-example"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger = "0.5"
actix = "0.5"
actix-web = { version = "^0.5", features=["alpn"] }
openssl = { version="0.10" }
