[package]
name = "tls-example"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
workspace = ".."

[[bin]]
name = "tls-server"
path = "src/main.rs"

[dependencies]
env_logger = "0.5"
openssl = { version="0.10" }

actix-rt = "0.2"
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0", features=["ssl"] }
