[package]
name = "async_db"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.3"

env_logger = "0.9"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
log = "0.4"
r2d2 = "0.8"
r2d2_sqlite = "0.19"
rusqlite = "0.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
