[package]
name = "actix-web-cors"
version = "0.1.0"
authors = ["krircc <krircc@aliyun.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
http = "0.1"

actix = "0.5"
actix-web = "^0.5"
dotenv = "0.10"
env_logger = "0.5"
futures = "0.1"
