[package]
name = "actix-web-cors"
version = "1.0.0"
authors = ["krircc <krircc@aliyun.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-cors = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.7"
futures = "0.3"
