[package]
name = "middleware-encrypted-payloads"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-http.workspace = true
actix-web.workspace = true
actix-web-lab.workspace = true

aes-gcm-siv = "0.11"
base64 = "0.21"
env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
pin-project = "1"
serde.workspace = true
serde_json.workspace = true
