[package]
name = "rustls-client-cert"
version = "1.0.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2018"

[dependencies]
actix-tls = "2"
actix-web = { version = "3", features = ["rustls"] }
env_logger = "0.8"
log = "0.4"
rustls = "0.18"
