[package]
name = "juniper-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
actix-web-lab = { workspace = true }
actix-cors = { workspace = true }

juniper = "0.15"

env_logger.workspace = true
log.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
