[package]
name = "juniper-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.3"
actix-web-lab = "0.10"
actix-cors = "0.6.0-beta.10"

juniper = "0.15"

env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
