[package]
name = "juniper-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.18"
actix-cors = "0.6"

juniper = "0.15"

env_logger = "0.10"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
