[package]
name = "run-in-thread"
version = "1.0.0"
edition = "2021"
description = "Run Actix Web in separate thread"

[dependencies]
actix-web.workspace = true

env_logger.workspace = true
log.workspace = true
