[package]
name = "background-jobs"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true

anyhow = "1"
apalis = { version = "0.3", features = ["redis"] }
chrono = { version = "0.4.20", default-features = false, features = ["clock", "serde"] }
dotenv = "0.15"
env_logger.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7.4"
