[package]
name = "multipart-example"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Simple file uploader in Actix Web with Async/Await"
keywords = ["actix", "actix-web", "multipart"]
repository = "https://github.com/actix/examples"
readme = "README.md"

[dependencies]
actix-multipart = "0.4"
actix-web = "4"

futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
sanitize-filename = "0.4"
uuid = { version = "1", features = ["v4"] }
