[package]
name = "simple-auth-server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-identity.workspace = true
actix-session = { workspace = true, features = ["cookie-session"] }
actix-web.workspace = true

chrono = { version = "0.4.20", features = ["serde"] }
derive_more.workspace = true
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
dotenv = "0.15"
env_logger.workspace = true
log = "0.4"
once_cell = "1"
r2d2 = "0.8"
rust-argon2 = "1"
serde_json.workspace = true
serde.workspace = true
sparkpost = "0.5"
time = "0.3"
uuid = { version = "1", features = ["v4", "serde"] }
