[package]
name = "simple-auth-server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-identity = "0.4.0-beta.8"

chrono = { version = "0.4.6", features = ["serde"] }
derive_more = "0.99.0"
diesel = { version = "1.4.5", features = ["postgres", "uuidv07", "r2d2", "chrono"] }
dotenv = "0.15"
env_logger = "0.9.0"
futures = "0.3.1"
r2d2 = "0.8"
rust-argon2 = "1.0.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sparkpost = "0.5.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
time = "0.3.7"
