[package]
name = "async_pg"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
config = "0.13.1"
deadpool-postgres = { version = "0.11", features = ["serde"] }
derive_more.workspace = true
dotenv = "0.15.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio-pg-mapper = "0.2.0"
tokio-pg-mapper-derive = "0.2.0"
tokio-postgres = "0.7.6"
