[package]
name = "template_handlebars"
version = "1.0.0"
authors = ["Alexandru Tiniuc <tiniuc.alexandru@gmail.com>"]
edition = "2021"

[dependencies]
actix-http = "2"
actix-web = "3"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"
