[package]
name = "websocket-example"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
actix = "0.12"
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4"

env_logger = "0.9"
log = "0.4"
rand = "0.8"
serde = "1"
serde_json = "1"
