[package]
name = "templating-minijinja"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.18"
actix-utils = "3"

env_logger = "0.10"
log = "0.4"
minijinja = { version = "0.24", features = ["source"] }
minijinja-autoreload = "0.24"
