[package]
name = "tls-acme"
edition.workspace = true
rust-version.workspace = true

[dependencies]
acme-rfc8555 = "0.1"
actix-files.workspace = true
actix-web = { workspace = true, features = ["rustls-0_23"] }
color-eyre.workspace = true
env_logger.workspace = true
eyre.workspace = true
log.workspace = true
rustls.workspace = true
tokio = { workspace = true, features = ["fs"] }
