[package]
name = "tls-acme"
version = "1.0.0"
publish = false
edition.workspace = true

[dependencies]
acme-rfc8555 = "0.1"
actix-files.workspace = true
actix-web = { workspace = true, features = ["rustls"] }
color-eyre = "0.6"
env_logger.workspace = true
eyre = "0.6"
log.workspace = true
rustls = "0.21"
rustls-pemfile = "1"
tokio = { workspace = true, feature = ["fs"] }
