[package]
name = "openssl-auto-le"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true, features = ["openssl"] }
actix-files = { workspace = true }

acme-micro = "0.12"
anyhow = "1"
env_logger.workspace = true
log.workspace = true
openssl = { version = "0.10", features = ["v110"] }
reqwest = "0.11"
