[package]
name = "openssl-auto-le"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
actix-files = "0.6"

acme-micro = "0.12"
anyhow = "1"
env_logger = "0.9"
log = "0.4"
openssl = { version = "0.10", features = ["v110"] }
reqwest = "0.11"
