[package]
name = "rustls-client-cert"
version = "1.0.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2021"

[dependencies]
actix-tls = "3.0"
actix-web = { version = "4.0.0-rc.1", features = ["rustls"] }
env_logger = "0.9"
log = "0.4"
rustls = "0.20.2"
rustls-pemfile = "0.2.1"
