[package]
name = "form-example"
version = "0.1.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-web = "1.0.0-beta.3"

serde = "1.0"
serde_derive = "1.0"
