[package]
name = "form-example"
version = "1.0.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.1"
serde = { version = "1", features = ["derive"] }
