[package]
name = "middleware-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-http = "3"

env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
pin-project = "1"
