[package]
name = "basics"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0.0-alpha.4"
actix-files = "0.1.0-alpha.4"
actix-session = "0.1.0-alpha.4"

futures = "0.1.25"
env_logger = "0.5"
bytes = "0.4"
