[package]
name = "actix_redis"
version = "1.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2021"

[dependencies]
actix = "0.10"
actix-web = "3"
actix-redis = "0.9"
futures = "0.3"
redis-async = "0.6.3"
serde = { version = "1", features = ["derive"] }
env_logger = "0.8"
