[package]
name = "awc_https"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
awc = { version = "3", features = ["rustls"] }

env_logger = "0.10"
log = "0.4"
mime = "0.3"
rustls = "0.20"
webpki-roots = "0.22"
