[package]
name = "websocket-chat-actorless-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web = "4"
actix-ws = "0.2.5"
awc = "3"

derive_more = "0.99.5"
env_logger = "0.9"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
rand = "0.8"
tokio = { version = "1.13.1", features = ["rt", "macros", "sync", "time"] }
