[package]
name = "db-redis"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"

env_logger = "0.9"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
redis = { version = "0.22", default-features = false, features = ["tokio-comp", "connection-manager"] }
serde = { version = "1", features = ["derive"] }
