[package]
name = "websocket-tcp-example"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-tcp-server"
path = "src/main.rs"

[[bin]]
name = "websocket-tcp-client"
path = "src/client.rs"

[dependencies]
actix = "0.12"
actix-codec = "0.4.1"
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4.0.0-beta.11"

byteorder = "1.2"
bytes = "1"
env_logger = "0.9"
futures = "0.3"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.13.1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1.8"
