[package]
name = "websocket-tcp-example"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-tcp-server"
path = "src/main.rs"

[[bin]]
name = "websocket-tcp-client"
path = "src/client.rs"

[dependencies]
actix = "0.13"
actix-codec = "0.5"
actix-files = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }

byteorder = "1.2"
bytes = "1"
env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std", "sink"] }
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.13.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1.8"
