[package]
name = "simple-auth-server"
version = "2.0.0"
authors = ["mygnu <tech@hgill.io>"]
edition = "2018"
workspace = "../.."

[dependencies]
actix-web = "3"
actix-identity = "0.3"

chrono = { version = "0.4.6", features = ["serde"] }
derive_more = "0.99.0"
diesel = { version = "1.4.5", features = ["postgres", "uuidv07", "r2d2", "chrono"] }
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3.1"
r2d2 = "0.8"
rust-argon2 = "0.8"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sparkpost = "0.5.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
time = "0.2"
