[package]
name = "jsonrpc-example"
version = "2.0.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"

bytes = "1.1.0"
env_logger = "0.9.0"
futures-util = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
