[package]
name = "jsonrpc-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"

bytes = "1.1.0"
env_logger = "0.9.0"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
