[package]
name = "server-sent-events"
version = "1.0.0"
authors = ["Arve Seljebu"]
edition = "2018"

[dependencies]
actix-web = "3"
env_logger = "0.8"
futures = "0.3.1"
tokio = { version = "0.2", features = ["sync"] }
