[package]
name = "server-sent-events"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.18"
env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
parking_lot = "0.12"
tokio = { version = "1.13.1", features = ["sync"] }
tokio-stream = { version = "0.1.8", features = ["time"] }
