[package]
name = "websocket-autobahn"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "websocket-autobahn-server"
path = "src/main.rs"

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4.1"

env_logger = "0.9"
log = "0.4"
