[package]
name = "openssl-example"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-rt = "1.0.0"
actix-web = { version="2.0.0-rc", features=["openssl"] }
env_logger = "0.6"
openssl = "0.10"
