[package]
name = "basics"
version = "2.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-files = "0.6.0-beta.15"
actix-session = "0.5.0-beta.7"

async-stream = "0.3"
env_logger = "0.9"
log = "0.4"
tokio = "1"
