[package]
name = "cookie-auth"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "3"
actix-identity = "0.3"
env_logger = "0.8"
rand = "0.7"
