[package]
name = "error_handling"
version = "0.1.0"
authors = ["dowwie <dkcdkg@gmail.com>"]

[dependencies]
actix = "0.7.3"
actix-web = "0.7.3"
failure = "0.1.2"
futures = "0.1.23"
rand = "0.5.4"
env_logger = "0.5.12"
