[package]
name = "error_handling"
version = "0.1.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0" }

derive_more = "0.14.0"
futures = "0.1.23"
rand = "0.5.4"
env_logger = "0.6"
