[package]
name = "cookie-session"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"
actix-session = "0.5.0-beta.7"
log = "0.4"
env_logger = "0.9.0"
