[package]
name = "template-tinytemplate"
version = "2.0.0"
authors = ["Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.8"
tinytemplate = "1.1"
actix-http = "2"
actix-web = "3"
serde_json = "1"
