[package]
name = "simple-auth-server"
version = "2.0.0"
authors = ["mygnu <tech@hgill.io>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-identity = "0.2.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
argonautica = "0.2.0"
chrono = { version = "0.4.6", features = ["serde"] }
derive_more = "0.99.0"
diesel = { version = "1.4.2", features = ["postgres","uuidv07", "r2d2", "chrono"] }
dotenv = "0.14.1"
env_logger = "0.6"
futures = "0.3.1"
r2d2 = "0.8"
lazy_static = "1.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sparkpost = "0.5.2"
uuid = { version = "0.7", features = ["serde", "v4"] }
