[package]
name = "static_index"
version = "0.1.0"
authors = ["Jose Marinez <digeratus@gmail.com>"]
workspace = "../"

[dependencies]
futures = "0.1"
env_logger = "0.5"
actix = "0.5"
actix-web = "0.6"
