[package]
name = "rustls-example"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "rustls-server"
path = "src/main.rs"

[dependencies]
env_logger = "0.8"
rustls = "0.18"
actix-web = { version = "3", features = ["rustls"] }
actix-files = "0.3"
