[package]
name = "http-proxy"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
awc = "3.0.0-beta.21"

clap = { version = "3", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
url = "2.2"
