[package]
name = "http-proxy"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "Rotem Yaari <vmalloc@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = { version = "2.0.0", features=["openssl"] }
clap = "2.32.0"
futures = "0.3.1"
failure = "0.1.3"
url = "1.7.1"
