[package]
name = "cors"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true, features = ["rustls"] }
actix-cors.workspace = true

env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
