[package]
name = "actix-web-cors"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["rustls"] }
actix-cors = "0.6"

env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
