[package]
name = "rustls-client-cert"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-tls = "3.0"
actix-web = { version = "4", features = ["rustls"] }
env_logger = "0.10"
log = "0.4"
rustls = "0.20"
rustls-pemfile = "1"
