[package]
name = "websocket-example"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
actix-rt = "1.0.0"
actix = "0.9.0-alpha.1"
actix-web = "2.0.0-alpha.5"
actix-web-actors = "2.0.0-alpha.1"
actix-files = "0.2.0-alpha.3"

rand = "0.6"
bytes = "0.5.3"
byteorder = "1.1"
futures = "0.3.1"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
