[package]
name = "openssl-example"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
env_logger = "0.8"
openssl = "0.10"
