[package]
name = "redis_session"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-session = "0.4"
actix-redis = "0.9"
env_logger = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
actix-service = "1"
actix-http = "2"
rand = "0.7.3"
time = "0.2"

[dev-dependencies]
actix-rt = "1"
