[package]
name = "template_handlebars"
version = "1.0.0"
authors = ["Alexandru Tiniuc <tiniuc.alexandru@gmail.com>"]
edition = "2018"

[dependencies]
actix-http = "1.0.1"
actix-rt = "1.0.0"
actix-web = "2.0.0"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"
