[package]
name = "json-validation"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
awc = { version = "3", features = ["openssl"] }

env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
validator = { version = "0.16", features = ["derive"] }
