[package]
name = "redis_session"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0-alpha.6"
actix-session = "0.3.0-alpha.3"
actix-redis = { version = "0.8.0-alpha.1", features = ["web"] }
env_logger = "0.6"
serde = { version = "^1.0", features = ["derive"] }
actix-service = "1.0.0"
actix-http = "1.0.0"
serde_json = "1.0.40"
time = "0.1.42"
