[package]
name = "cookie-session"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
actix-web = "2.0.0-alpha.6"
actix-session = "0.3.0-alpha.3"
actix-rt = "1.0.0"

futures = "0.3.1"
time = "0.1"
env_logger = "0.6"
