[package]
name = "cookie-session"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.3"
actix-session = "0.1.0-alpha.3"

futures = "0.1"
time = "0.1"
env_logger = "0.6"
