[package]
name = "protobuf-example"
version = "0.2.0"
edition = "2021"

[dependencies]
actix = "0.10"
actix-protobuf = "0.6"
actix-web = "3"

bytes = "0.5.4"
env_logger = "0.9"
prost = "0.6"
prost-derive = "0.6"
