[package]
name = "middleware-example"
version = "0.1.0"
authors = ["Gorm Casper <gcasper@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-service = "0.3.3"
actix-web = "1.0.0-alpha.3"
futures = "0.1.25"
env_logger = "0.6"