[package]
name = "middleware-example"
version = "0.1.0"
authors = ["Gorm Casper <gcasper@gmail.com>", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
actix-service = "0.4.1"
actix-web = "1.0.0"
futures = "0.1.25"
env_logger = "0.6"
bytes = "0.4"
