[package]
name = "template_yarte"
version = "0.0.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
publish = false
edition = "2018"

workspace = ".."

[dependencies]
env_logger = "0.7"

yarte = { git = "https://github.com/botika/yarte", features = ["with-actix-web"]  }

actix-rt = "1.0"
actix-web = "2.0.0-rc"

[build-dependencies]
yarte = { git = "https://github.com/botika/yarte", features = ["with-actix-web"]  }

[dev-dependencies]
bytes = "0.4"
