[package]
name = "r2d2-example"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.21"

env_logger = "0.9.0"
uuid = { version = "1.0.0-alpha.1", features = ["v4"] }

r2d2 = "0.8"
r2d2_sqlite = "0.19.0"
rusqlite = "0.26.3"
