[package]
name = "rustls-example"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "rustls-server"
path = "src/main.rs"

[dependencies]
env_logger = "0.9"
rustls = "0.20.2"
rustls-pemfile = "0.2.1"
actix-web = { version = "4", features = ["rustls"] }
actix-files = "0.6"
