[package]
name = "rustls-example"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "rustls-server"
path = "src/main.rs"

[dependencies]
actix-web = { workspace = true, features = ["rustls"] }
actix-files.workspace = true

env_logger.workspace = true
log.workspace = true
rustls = "0.20.2"
rustls-pemfile = "1"
