[package]
name = "json_error"
version = "1.0.0"
authors = ["Kai Yao <kai.b.yao@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.1"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
