[package]
name = "http-proxy"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>", "Rotem Yaari <vmalloc@gmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
clap = "2.33"
url = "2.0"
