[package]
name = "middleware-http-to-https"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.18"

env_logger = "0.9"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
rustls = "0.20"
rustls-pemfile = "1"
