[package]
name = "unix-socket"
version = "0.1.0"
authors = ["Messense Lv <messense@icloud.com>"]
workspace = "../"

[dependencies]
env_logger = "0.5"
actix = "0.5"
actix-web = "^0.6"
tokio-uds = "0.1"
