[package]
name = "unix-socket"
version = "1.0.0"
authors = ["Messense Lv <messense@icloud.com>"]
workspace = ".."
edition = "2018"

[dependencies]
env_logger = "0.6"
actix-web = "2.0.0"
actix-rt = "1.0.0"
