[package]
name = "async-graphql-demo"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2021"

[dependencies]
actix-web = "3.0.0"
async-graphql = "2.0.0"
async-graphql-actix-web = "2.0.0"
slab = "0.4.2"
