[package]
name = "multipart-s3-example"
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-multipart.workspace = true
actix-web.workspace = true
actix-web-lab.workspace = true

aws-config = "1"
aws-sdk-s3 = "1"

dotenvy.workspace = true
env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "fs"] }
tokio-util = "0.7"
