[package]
name = "multipart-s3-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-multipart.workspace = true
actix-web.workspace = true
actix-web-lab.workspace = true

aws-config = "0.55"
aws-sdk-s3 = "0.28"

dotenv = "0.15"
env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "fs"] }
