[package]
name = "multipart-s3-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-multipart = "0.4"
actix-web = { workspace = true }
actix-web-lab = "0.18"

aws-config = "0.51"
aws-sdk-s3 = "0.21"

dotenv = "0.15"
env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
sanitize-filename = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.13.1", features = ["io-util", "fs"] }
