[package]
name = "async_data_factory"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
num_cpus = "1.13"
redis = { version = "0.16.0", default-features = false, features = ["tokio-rt-core"] }
# redis_tang is an redis pool for test purpose
redis_tang = "0.1"
