[package]
name = "http-full-proxy"
version = "0.1.0"
authors = ["Rotem Yaari"]
workspace = ".."
edition = "2018"

[dependencies]
actix-rt = "0.2"
actix-web = "1.0.0-alpha.2"

clap = "2.32.0"
futures = "0.1.25"
failure = "0.1.3"
url = "1.7.1"
