[package]
name = "todo"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files.workspace = true
actix-session = { workspace = true, features = ["cookie-session"] }
actix-web.workspace = true
actix-web-lab.workspace = true

dotenv = "0.15"
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite"] }
tera = "1.5"
