[package]
name = "todo"
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-files.workspace = true
actix-session = { workspace = true, features = ["cookie-session"] }
actix-web.workspace = true

dotenvy.workspace = true
env_logger.workspace = true
log.workspace = true
serde.workspace = true
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite"] }
tera = "1.5"
