[package]
name = "todo"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-rc.3"
actix-files = "0.6.0-beta.16"
actix-session = "0.5.0-beta.7"

dotenv = "0.15"
env_logger = "0.9"
futures-util = "0.3.7"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tera = "1.5"

[dependencies.sqlx]
features = ["runtime-tokio-rustls", "sqlite", "offline"]
version = "0.5.10"
