[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
workspace = ".."

[[bin]]
name = "websocket-server"
path = "src/main.rs"

#[[bin]]
#name = "websocket-client"
#path = "src/client.rs"

[dependencies]
actix = "0.8.0-alpha.1"
actix-web = "1.0.0-alpha.1"
actix-web-actors = "1.0.0-alpha.1"
actix-files = "0.1.0-alpha.1"
env_logger = "0.6"
futures = "0.1"
bytes = "0.4"