[package]
name = "websocket"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
workspace = ".."

[[bin]]
name = "websocket-server"
path = "src/main.rs"

#[[bin]]
#name = "websocket-client"
#path = "src/client.rs"

[dependencies]
actix = { git="https://github.com/actix/actix.git" }
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
actix-web-actors = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
actix-files = { git="https://github.com/actix/actix-web.git", branch = "1.0" }
env_logger = "0.6"
futures = "0.1"
bytes = "0.4"