[package]
name = "redis-session-example"
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-session = { workspace = true, features = ["redis-session"] }
actix-web.workspace = true

env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
actix-test.workspace = true
time.workspace = true
