[package]
name = "redis_session"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.6", features = ["redis-actor-session"] }

env_logger = "0.9"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
actix-test = "0.1.0-beta.11"
time = "0.3.7"
