[package]
name = "template-askama"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = ".."
edition = "2018"

[dependencies]
env_logger = "0.6"
askama = "0.6"
actix-web = { git="https://github.com/actix/actix-web.git", branch = "1.0" }

[build-dependencies]
askama = "0.6"
