[package]
name = "template-askama"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"

[dependencies]
env_logger = "0.5"
actix = "0.5"
actix-web = "^0.5"
askama = "0.6"

[build-dependencies]
askama = "0.6"
